(cl:defpackage navigation-srv
  (:use )
  (:export
   "GETAMCLPOSE"
   "<GETAMCLPOSE-REQUEST>"
   "GETAMCLPOSE-REQUEST"
   "<GETAMCLPOSE-RESPONSE>"
   "GETAMCLPOSE-RESPONSE"
   "GETPIXELPOSE"
   "<GETPIXELPOSE-REQUEST>"
   "GETPIXELPOSE-REQUEST"
   "<GETPIXELPOSE-RESPONSE>"
   "GETPIXELPOSE-RESPONSE"
  ))

