(cl:defpackage bumperbot_examples-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "GETTRANSFORM"
   "<GETTRANSFORM-REQUEST>"
   "GETTRANSFORM-REQUEST"
   "<GETTRANSFORM-RESPONSE>"
   "GETTRANSFORM-RESPONSE"
  ))

