// Generated by gencpp from file navigation/GetAmclPoseRequest.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_GETAMCLPOSEREQUEST_H
#define NAVIGATION_MESSAGE_GETAMCLPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigation
{
template <class ContainerAllocator>
struct GetAmclPoseRequest_
{
  typedef GetAmclPoseRequest_<ContainerAllocator> Type;

  GetAmclPoseRequest_()
    {
    }
  GetAmclPoseRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::navigation::GetAmclPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation::GetAmclPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetAmclPoseRequest_

typedef ::navigation::GetAmclPoseRequest_<std::allocator<void> > GetAmclPoseRequest;

typedef boost::shared_ptr< ::navigation::GetAmclPoseRequest > GetAmclPoseRequestPtr;
typedef boost::shared_ptr< ::navigation::GetAmclPoseRequest const> GetAmclPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation::GetAmclPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation::GetAmclPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::navigation::GetAmclPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::GetAmclPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::GetAmclPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::GetAmclPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::GetAmclPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::GetAmclPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation::GetAmclPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::navigation::GetAmclPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation::GetAmclPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation/GetAmclPoseRequest";
  }

  static const char* value(const ::navigation::GetAmclPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation::GetAmclPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Request\n"
;
  }

  static const char* value(const ::navigation::GetAmclPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation::GetAmclPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetAmclPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation::GetAmclPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::navigation::GetAmclPoseRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_MESSAGE_GETAMCLPOSEREQUEST_H
