// Generated by gencpp from file navigation/GetAmclPose.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_GETAMCLPOSE_H
#define NAVIGATION_MESSAGE_GETAMCLPOSE_H

#include <ros/service_traits.h>


#include <navigation/GetAmclPoseRequest.h>
#include <navigation/GetAmclPoseResponse.h>


namespace navigation
{

struct GetAmclPose
{

typedef GetAmclPoseRequest Request;
typedef GetAmclPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetAmclPose
} // namespace navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navigation::GetAmclPose > {
  static const char* value()
  {
    return "4f3e0bbe7a24e1f929488cd1970222d3";
  }

  static const char* value(const ::navigation::GetAmclPose&) { return value(); }
};

template<>
struct DataType< ::navigation::GetAmclPose > {
  static const char* value()
  {
    return "navigation/GetAmclPose";
  }

  static const char* value(const ::navigation::GetAmclPose&) { return value(); }
};


// service_traits::MD5Sum< ::navigation::GetAmclPoseRequest> should match
// service_traits::MD5Sum< ::navigation::GetAmclPose >
template<>
struct MD5Sum< ::navigation::GetAmclPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navigation::GetAmclPose >::value();
  }
  static const char* value(const ::navigation::GetAmclPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation::GetAmclPoseRequest> should match
// service_traits::DataType< ::navigation::GetAmclPose >
template<>
struct DataType< ::navigation::GetAmclPoseRequest>
{
  static const char* value()
  {
    return DataType< ::navigation::GetAmclPose >::value();
  }
  static const char* value(const ::navigation::GetAmclPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navigation::GetAmclPoseResponse> should match
// service_traits::MD5Sum< ::navigation::GetAmclPose >
template<>
struct MD5Sum< ::navigation::GetAmclPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navigation::GetAmclPose >::value();
  }
  static const char* value(const ::navigation::GetAmclPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation::GetAmclPoseResponse> should match
// service_traits::DataType< ::navigation::GetAmclPose >
template<>
struct DataType< ::navigation::GetAmclPoseResponse>
{
  static const char* value()
  {
    return DataType< ::navigation::GetAmclPose >::value();
  }
  static const char* value(const ::navigation::GetAmclPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIGATION_MESSAGE_GETAMCLPOSE_H
