// Generated by gencpp from file navigation/GetPixelPose.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_GETPIXELPOSE_H
#define NAVIGATION_MESSAGE_GETPIXELPOSE_H

#include <ros/service_traits.h>


#include <navigation/GetPixelPoseRequest.h>
#include <navigation/GetPixelPoseResponse.h>


namespace navigation
{

struct GetPixelPose
{

typedef GetPixelPoseRequest Request;
typedef GetPixelPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPixelPose
} // namespace navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navigation::GetPixelPose > {
  static const char* value()
  {
    return "7c5941ad5d679949278959effa1051da";
  }

  static const char* value(const ::navigation::GetPixelPose&) { return value(); }
};

template<>
struct DataType< ::navigation::GetPixelPose > {
  static const char* value()
  {
    return "navigation/GetPixelPose";
  }

  static const char* value(const ::navigation::GetPixelPose&) { return value(); }
};


// service_traits::MD5Sum< ::navigation::GetPixelPoseRequest> should match
// service_traits::MD5Sum< ::navigation::GetPixelPose >
template<>
struct MD5Sum< ::navigation::GetPixelPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navigation::GetPixelPose >::value();
  }
  static const char* value(const ::navigation::GetPixelPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation::GetPixelPoseRequest> should match
// service_traits::DataType< ::navigation::GetPixelPose >
template<>
struct DataType< ::navigation::GetPixelPoseRequest>
{
  static const char* value()
  {
    return DataType< ::navigation::GetPixelPose >::value();
  }
  static const char* value(const ::navigation::GetPixelPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navigation::GetPixelPoseResponse> should match
// service_traits::MD5Sum< ::navigation::GetPixelPose >
template<>
struct MD5Sum< ::navigation::GetPixelPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navigation::GetPixelPose >::value();
  }
  static const char* value(const ::navigation::GetPixelPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation::GetPixelPoseResponse> should match
// service_traits::DataType< ::navigation::GetPixelPose >
template<>
struct DataType< ::navigation::GetPixelPoseResponse>
{
  static const char* value()
  {
    return DataType< ::navigation::GetPixelPose >::value();
  }
  static const char* value(const ::navigation::GetPixelPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIGATION_MESSAGE_GETPIXELPOSE_H
