// Generated by gencpp from file navigation/GetPixelPoseRequest.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_GETPIXELPOSEREQUEST_H
#define NAVIGATION_MESSAGE_GETPIXELPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigation
{
template <class ContainerAllocator>
struct GetPixelPoseRequest_
{
  typedef GetPixelPoseRequest_<ContainerAllocator> Type;

  GetPixelPoseRequest_()
    {
    }
  GetPixelPoseRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::navigation::GetPixelPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation::GetPixelPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetPixelPoseRequest_

typedef ::navigation::GetPixelPoseRequest_<std::allocator<void> > GetPixelPoseRequest;

typedef boost::shared_ptr< ::navigation::GetPixelPoseRequest > GetPixelPoseRequestPtr;
typedef boost::shared_ptr< ::navigation::GetPixelPoseRequest const> GetPixelPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation::GetPixelPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation::GetPixelPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::navigation::GetPixelPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::GetPixelPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::GetPixelPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::GetPixelPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::GetPixelPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::GetPixelPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation::GetPixelPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::navigation::GetPixelPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation::GetPixelPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation/GetPixelPoseRequest";
  }

  static const char* value(const ::navigation::GetPixelPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation::GetPixelPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Request\n"
;
  }

  static const char* value(const ::navigation::GetPixelPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation::GetPixelPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPixelPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation::GetPixelPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::navigation::GetPixelPoseRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_MESSAGE_GETPIXELPOSEREQUEST_H
